### ISSUE TITLE
IDMU: Finished

### ISSUE THREAD

**Issue by PatoRoxo** [thoughtsunificator/instagram-dm-unsender#24]
I tried to use this script as an alternative to the other one but every time I click "Unsend all DMs", it just scrolls up and after a few seconds it says IDMU: Finished but it didn't delete anything. I'm not a coder so I don't understand if I'm doing anything wrong,
I'm using Google Chrome

**Comment by gl4d** [comment]
same issue happening, it's loading a few msgs pages up and then displaying "IDMU: Finished", even if i manually load all the pages, i get the same message but it deleted 0 message.

using latest version of IDMU & chrome

**Comment by Teko012** [comment]
It is indeed seems to be broken. @thoughtsunificator do you think this issue is fixable?

**Comment by thoughtsunificator** [comment]
Could you post your console logs please ?

**Comment by Teko012** [comment]
> Could you post your console logs please ?

This is the only line that shows up along with the popup:

`unsend-strategy.js:138 TypeError: clickTarget.click is not a function
    at clickElementAndWaitFor (async-events.js:39:14)
    at UIMessage.clickElementAndWaitFor (ui-component.js:32:10)
    at UIMessage.openActionsMenu (ui-message.js:72:40)
    at UIMessage.isMyOwnMessage (ui-message.js:26:47)
    at async findMessages (dom-lookup.js:14:26)
    at async DefaultUI.createUIPIMessages (default-ui.js:41:27)
    at async #processBatches (unsend-strategy.js:125:29)
    at async #startUnsending (ui.js:83:3)
#processBatches @ unsend-strategy.js:138
await in #processBatches (async)
run @ unsend-strategy.js:88
#startUnsending @ ui.js:83
#onUnsendThreadMessagesButtonClick @ ui.js:161
(anonymous) @ ui.js:63
`

**Comment by thoughtsunificator** [comment]
@Teko012 Thans, I managed to reproduce the bug and am working on a fix. Will be releasing it ASAP.

**Comment by thoughtsunificator** [comment]
Fixed in https://github.com/thoughtsunificator/instagram-dm-unsender/releases/tag/v0.5.15

**Comment by Teko012** [comment]
@thoughtsunificator It seems to be indeed fixed, thanks, however, it seems like it's still not working properly. It unsends 2 messages, and then it writes Finished, even though there are way more messages still on the screen loaded. Can you maybe check that as well?

**Comment by Teko012** [comment]
Also, I checked it a bit further, but nothing shows in the console either, it just pretends its finished.

**Comment by PatoRoxo** [comment]
I am now running the v0.5.15 but the same thing happens as I said in my first comment. It scrolls up, loads for a while and says "IDMU: Finished". After that, I can't scroll down to see the dms unless I refresh the page.

**Comment by thoughtsunificator** [comment]
Yep I got the same issue on another thread. I am looking into it thanks for the heads up !

**Comment by Teko012** [comment]
yeah, I also noticed the scrolling getting stuck aftwards. Thanks for checking it!

**Comment by thoughtsunificator** [comment]
I have released a new version, please check it and let me know.

**Comment by Teko012** [comment]
I tested now with `0.5.16`, but I still observe the same behaviour: it deletes one message, then says Finished, and constantly trying to scroll up afterwards.

**Comment by gl4d** [comment]
also still having problems here, using 0.5.16
it scroll up, sometimes it delete a few messages but most of the time it deletes nothing, ignores a LOT of messages and just pops up the "IDMU: Finished"

from my understanding (and in my case): the bot seems to assume that there's nothing to delete if the other person sent multiple messages in a row, even tho there might be some but just a little bit further down

here's an exemple: https://www.youtube.com/watch?v=HZp3cuGQYnI

**Comment by thoughtsunificator** [comment]
> also still having problems here, using 0.5.16 it scrolls up, sometimes its deleting a few messages but most of the time it deletes nothing, ignores a LOT of messages and just pops up the "IDMU: Finished"
> 
> from my understanding (and in my case): the bot seems to assume that there's nothing to delete if the other person sent multiple messages in a row, even tho there might be some but just a little bit further down
> 
> here's an exemple: https://www.youtube.com/watch?v=HZp3cuGQYnI

Thanks I'll look into it !

**Comment by Teko012** [comment]
Great, thank you!

**Comment by sorryzzss** [comment]
Thanks

**Comment by Teko012** [comment]
@thoughtsunificator Do you happen to have any progress on this by any chance?

**Comment by thoughtsunificator** [comment]
> @thoughtsunificator Do you happen to have any progress on this by any chance?

Sorry for the late reply, I'm still in the process of writing more tests and reworking the batch process.

**Comment by thoughtsunificator** [comment]
0.5.17 is out, I believe most things have been fixed.

**Comment by Teko012** [comment]
@thoughtsunificator Thank you for the work, it seems to be indeed working. There is a bug I experience, sometimes it gets stuck on `Found X messages, unsending...` and doesn't continue until a refresh and starting it again. Nothing is shown in the console.

**Comment by DirectGames** [comment]
Still doesn't work indeed. Keeps looking for messages but doesn't delete.

**Comment by thoughtsunificator** [comment]
@DirectGames Do you have any console logs I can look at.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by gl4d** [comment]
Same here; It looks for a few msgs and successfully deletes them, successfully load some pages up but it instantly gets stuck when there's a lot/a few messages in a row, only from the other person.
stopping and starting the script kinda "works" but takes a lot of times since it doesn't scroll up much and gets stuck pretty fast.

**Comment by thoughtsunificator** [comment]
There's still an issue when the interlocutor messages makes up the entire chat window, as I said earlier, for some reason Instagram removes message from the DOM they are no longer in the viewport.

A temporary workaround would be to scroll up to your oldest message manually.

I will release another fix soon.

**Comment by brog-io** [comment]
I'm also experiencing this issue, I also can't see batch size and Load all DMs. This might be due me being on the EU version of the site. I hope this gets fixed and it seems this is the only script that can delete all DMs.

**Comment by DirectGames** [comment]
> I'm also experiencing this issue, I also can't see batch size and Load all DMs. This might be due me being on the EU version of the site. I hope this gets fixed and it seems this is the only script that can delete all DMs.

I made a userscript that works for EU. https://github.com/DirectGames/instagramdmunsender

**Comment by thoughtsunificator** [comment]
> I'm also experiencing this issue, I also can't see batch size and Load all DMs. This might be due me being on the EU version of the site. I hope this gets fixed and it seems this is the only script that can delete all DMs.

I removed these buttons in the newer versions no worry.

**Comment by thoughtsunificator** [comment]
I just released v0.5.17-patched. Hope it works for you.

**Comment by DirectGames** [comment]
Still doesn't work (EU)

**Comment by PatoRoxo** [comment]
Tried to run it, looked like it was doing something for a few seconds then it said "IDMU:Finished" and then "Done. 0 messages unsent." right next to the button to unsend.

I just get this in the console. 
DOMException: Aborted
loadMoreMessages @ dom-lookup.js:66
await in loadMoreMessages (async)
fetchAndRenderThreadNextMessagePage @ ui-messages-wrapper.js:13
fetchAndRenderThreadNextMessagePage @ default-ui.js:33
fetchAndRenderThreadNextMessagePage @ uipi.js:40
fetchAndRenderThreadNextMessagePage @ idmu.js:43
#next @ unsend-strategy.js:117
await in #next (async)
run @ unsend-strategy.js:88
#startUnsending @ ui.js:90
#onUnsendThreadMessagesButtonClick @ ui.js:125
(anonymous) @ ui.js:73

**Comment by Teko012** [comment]
For me, the previous version worked, this one doesn't do anything at all.

**Comment by thoughtsunificator** [comment]
Note: There's been yet another change in Instagram UI : 

 ![2024-02-01_21-12](https://github.com/thoughtsunificator/instagram-dm-unsender/assets/85041649/a5adeeac-ed27-4c26-a1e5-7bb97e8ec4ee)

**Comment by exuded** [comment]
any fix yet? still not working

**Comment by thoughtsunificator** [comment]
@exuded can you file a new issue ?

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thoughtsunificator** [comment]
Looks like there are multiple issues here, so I'll ask that you file a new bug if you still have one while making sure to include all details.
